import type { Category, Product, Order, User, DeliveryZone, Promotion, DashboardStats } from "./types"

export const mockCategories: Category[] = [
  { id: "tortas", name: "Tortas", slug: "tortas", isActive: true, description: "Tortas completas o por porción" },
  {
    id: "tres_leches",
    name: "Postre de 3 Leches",
    slug: "tres-leches",
    isActive: true,
    description: "Con crema chantilly y fresas",
  },
  { id: "brownies", name: "Brownies", slug: "brownies", isActive: true, description: "Brownie de chocolate con chips" },
  {
    id: "red_velvet",
    name: "Red Velvet",
    slug: "red-velvet",
    isActive: true,
    description: "Con cobertura de queso crema",
  },
  {
    id: "pie_limon",
    name: "Pie de Limón",
    slug: "pie-limon",
    isActive: true,
    description: "Con masa quebrada y merengue",
  },
  {
    id: "churros",
    name: "Churros",
    slug: "churros",
    isActive: true,
    description: "Con glaseado de azúcar y chocolate",
  },
  { id: "donas", name: "Donas", slug: "donas", isActive: true, description: "Vainilla y chocolate con toppings" },
  {
    id: "fresas",
    name: "Fresas con Crema",
    slug: "fresas-con-crema",
    isActive: true,
    description: "Fresas frescas con crema chantilly",
  },
  {
    id: "cupcakes",
    name: "Cupcakes",
    slug: "cupcakes",
    isActive: true,
    description: "Vainilla, chocolate y más sabores",
  },
]

export const mockProducts: Product[] = [
  {
    id: 1,
    name: "Torta de Chocolate",
    slug: "torta-chocolate",
    category: "tortas",
    categoryName: "Tortas",
    image: "/delicious-chocolate-cake-with-frosting.jpg",
    description: "Deliciosa torta de chocolate con cobertura de ganache",
    stock: 15,
    isActive: true,
    basePrice: 100,
    variants: [
      { id: 1, type: "Torta Completa", price: 100 },
      { id: 2, type: "Por Porción", price: 20, unit: "porción" },
    ],
    customizations: [
      {
        id: "relleno",
        name: "Relleno",
        type: "filling",
        options: [
          { id: "chocolate", name: "Chocolate", priceModifier: 0 },
          { id: "arequipe", name: "Arequipe", priceModifier: 5 },
          { id: "frutas", name: "Frutas", priceModifier: 10 },
        ],
      },
      {
        id: "cobertura",
        name: "Cobertura",
        type: "glaze",
        options: [
          { id: "chocolate", name: "Chocolate", priceModifier: 0 },
          { id: "crema", name: "Crema Chantilly", priceModifier: 5 },
          { id: "fondant", name: "Fondant", priceModifier: 15 },
        ],
      },
    ],
  },
  {
    id: 2,
    name: "Brownie de Chocolate",
    slug: "brownie-chocolate",
    category: "brownies",
    categoryName: "Brownies",
    image: "/premium-chocolate-brownie-with-nuts.jpg",
    description: "Brownie de chocolate con chips de chocolate",
    stock: 20,
    isActive: true,
    price: 10,
    basePrice: 10,
    customizations: [
      {
        id: "toppings",
        name: "Toppings Extras",
        type: "topping",
        options: [
          { id: "nueces", name: "Nueces", priceModifier: 2 },
          { id: "helado", name: "Helado de Vainilla", priceModifier: 5 },
          { id: "salsa_chocolate", name: "Salsa de Chocolate", priceModifier: 2 },
        ],
      },
    ],
  },
  {
    id: 3,
    name: "Cupcakes",
    slug: "cupcakes",
    category: "cupcakes",
    categoryName: "Cupcakes",
    image: "/artisan-cookies-assortment.jpg",
    description: "Cupcakes de vainilla, chocolate, marmoleado entre otros sabores",
    stock: 50,
    isActive: true,
    basePrice: 5,
    variants: [
      { id: 1, type: "Individual", price: 5 },
      { id: 2, type: "5 unidades", price: 20 },
      { id: 3, type: "Docena", price: 50 },
    ],
    customizations: [
      {
        id: "sabor",
        name: "Sabor",
        type: "filling",
        options: [
          { id: "vainilla", name: "Vainilla", priceModifier: 0 },
          { id: "chocolate", name: "Chocolate", priceModifier: 0 },
          { id: "red_velvet", name: "Red Velvet", priceModifier: 2 },
          { id: "marmoleado", name: "Marmoleado", priceModifier: 0 },
        ],
      },
    ],
  },
  {
    id: 4,
    name: "Postre de 3 Leches",
    slug: "postre-tres-leches",
    category: "tres_leches",
    categoryName: "Postre de 3 Leches",
    image: "/strawberry-cheesecake.png",
    description: "Torta tres leches con cobertura de crema chantilly y fresas",
    stock: 12,
    isActive: true,
    price: 40,
    basePrice: 40,
    unit: "porción",
    variants: [
      { id: 1, type: "Porción", price: 40 },
      { id: 2, type: "Torta Completa", price: 120 },
    ],
  },
  {
    id: 5,
    name: "Churros",
    slug: "churros",
    category: "churros",
    categoryName: "Churros",
    image: "/oatmeal-cookies.png",
    description: "Deliciosos churros con glaseado de azúcar glas y chocolate (8-10 unidades)",
    stock: 30,
    isActive: true,
    price: 60,
    basePrice: 60,
    customizations: [
      {
        id: "salsa",
        name: "Salsa para Dipping",
        type: "topping",
        options: [
          { id: "chocolate", name: "Chocolate", priceModifier: 0 },
          { id: "arequipe", name: "Arequipe", priceModifier: 3 },
          { id: "mixto", name: "Mixto (Chocolate + Arequipe)", priceModifier: 5 },
        ],
      },
    ],
  },
  {
    id: 6,
    name: "Pastel Red Velvet",
    slug: "pastel-red-velvet",
    category: "red_velvet",
    categoryName: "Red Velvet",
    image: "/red-velvet-cake.png",
    description: "Torta Red Velvet con cobertura y relleno de queso crema",
    stock: 8,
    isActive: true,
    basePrice: 150,
    variants: [
      { id: 1, type: "Torta Completa", price: 150 },
      { id: 2, type: "Por Porción", price: 50, unit: "porción" },
    ],
  },
  {
    id: 7,
    name: "Pie de Limón",
    slug: "pie-limon",
    category: "pie_limon",
    categoryName: "Pie de Limón",
    image: "/delicious-carrot-cake.png",
    description: "Pie de limón con corteza de masa quebrada, crema de limón y esponjoso merengue",
    stock: 10,
    isActive: true,
    price: 10,
    basePrice: 10,
    unit: "porción",
  },
  {
    id: 8,
    name: "Donas",
    slug: "donas",
    category: "donas",
    categoryName: "Donas",
    image: "/french-macarons.jpg",
    description: "Deliciosas donas de vainilla y chocolate con el topping de tu preferencia",
    stock: 45,
    isActive: true,
    basePrice: 20,
    variants: [
      { id: 1, type: "3-5 unidades", price: 20 },
      { id: 2, type: "8-12 unidades", price: 60 },
    ],
    customizations: [
      {
        id: "masa",
        name: "Tipo de Masa",
        type: "doughType",
        options: [
          { id: "tradicional", name: "Tradicional", priceModifier: 0 },
          { id: "rellena", name: "Rellena", priceModifier: 5 },
        ],
      },
      {
        id: "glaseado",
        name: "Glaseado",
        type: "glaze",
        options: [
          { id: "chocolate", name: "Chocolate", priceModifier: 0 },
          { id: "vainilla", name: "Vainilla", priceModifier: 0 },
          { id: "fresa", name: "Fresa", priceModifier: 0 },
          { id: "glaseado_azucar", name: "Azúcar Glass", priceModifier: 0 },
        ],
      },
      {
        id: "toppings",
        name: "Toppings",
        type: "topping",
        options: [
          { id: "coco", name: "Coco Rallado", priceModifier: 1 },
          { id: "mani", name: "Maní", priceModifier: 1 },
          { id: "chispas", name: "Chispas de Colores", priceModifier: 1 },
          { id: "oreo", name: "Oreo Triturado", priceModifier: 2 },
        ],
      },
    ],
  },
  {
    id: 9,
    name: "Fresas con Crema",
    slug: "fresas-con-crema",
    category: "fresas",
    categoryName: "Fresas con Crema",
    image: "/strawberry-cheesecake.png",
    description: "Fresas frescas con el sabor de la crema chantilly",
    stock: 25,
    isActive: true,
    basePrice: 20,
    variants: [
      { id: 1, type: "Vaso Pequeño", price: 20 },
      { id: 2, type: "Vaso Grande", price: 40 },
    ],
    customizations: [
      {
        id: "toppings",
        name: "Toppings",
        type: "topping",
        options: [
          { id: "mani", name: "Maní", priceModifier: 2 },
          { id: "leche_condensada", name: "Leche Condensada", priceModifier: 3 },
          { id: "granola", name: "Granola", priceModifier: 2 },
          { id: "galleta", name: "Galleta Triturada", priceModifier: 2 },
          { id: "chocolate", name: "Chips de Chocolate", priceModifier: 3 },
        ],
      },
    ],
  },
]

export const mockDeliveryZones: DeliveryZone[] = [
  { id: "zona1", name: "Centro", price: 3, estimatedTime: "20-30 min", isActive: true },
  { id: "zona2", name: "Norte", price: 5, estimatedTime: "30-45 min", isActive: true },
  { id: "zona3", name: "Sur", price: 5, estimatedTime: "30-45 min", isActive: true },
  { id: "zona4", name: "Este", price: 7, estimatedTime: "45-60 min", isActive: true },
  { id: "zona5", name: "Oeste", price: 7, estimatedTime: "45-60 min", isActive: true },
]

export const mockOrders: Order[] = [
  {
    id: "1",
    orderNumber: "ORD-001",
    customerName: "María García",
    customerEmail: "maria@email.com",
    customerPhone: "0414-1234567",
    items: [
      {
        id: 1,
        productId: 1,
        productName: "Torta de Chocolate",
        productImage: "/delicious-chocolate-cake-with-frosting.jpg",
        quantity: 1,
        unitPrice: 100,
        totalPrice: 100,
      },
      {
        id: 2,
        productId: 2,
        productName: "Brownie de Chocolate",
        productImage: "/premium-chocolate-brownie-with-nuts.jpg",
        quantity: 2,
        unitPrice: 10,
        totalPrice: 20,
      },
    ],
    subtotal: 120,
    deliveryCost: 5,
    total: 125,
    status: "en_preparacion",
    deliveryType: "delivery",
    deliveryAddress: "Av. Principal, Casa 123",
    deliveryZone: "Norte",
    paymentMethod: "pago_movil",
    paymentStatus: "pagado",
    createdAt: "2025-01-27T10:30:00Z",
    updatedAt: "2025-01-27T10:45:00Z",
  },
  {
    id: "2",
    orderNumber: "ORD-002",
    customerName: "Carlos Rodríguez",
    customerEmail: "carlos@email.com",
    customerPhone: "0424-7654321",
    items: [
      {
        id: 3,
        productId: 9,
        productName: "Fresas con Crema",
        productImage: "/strawberry-cheesecake.png",
        quantity: 2,
        unitPrice: 40,
        totalPrice: 80,
      },
    ],
    subtotal: 80,
    deliveryCost: 0,
    total: 80,
    status: "recibido",
    deliveryType: "pickup",
    pickupTime: "15 minutos",
    paymentMethod: "efectivo",
    paymentStatus: "pendiente",
    createdAt: "2025-01-27T11:00:00Z",
    updatedAt: "2025-01-27T11:00:00Z",
  },
  {
    id: "3",
    orderNumber: "ORD-003",
    customerName: "Ana Martínez",
    customerEmail: "ana@email.com",
    customerPhone: "0412-9876543",
    items: [
      {
        id: 4,
        productId: 6,
        productName: "Pastel Red Velvet",
        productImage: "/red-velvet-cake.png",
        quantity: 1,
        unitPrice: 150,
        totalPrice: 150,
      },
    ],
    subtotal: 150,
    deliveryCost: 7,
    total: 157,
    status: "listo",
    deliveryType: "delivery",
    deliveryAddress: "Calle 5, Edificio Sol",
    deliveryZone: "Este",
    paymentMethod: "tarjeta",
    paymentStatus: "pagado",
    createdAt: "2025-01-27T09:00:00Z",
    updatedAt: "2025-01-27T11:30:00Z",
  },
]

export const mockUsers: User[] = [
  {
    id: 1,
    name: "María García",
    email: "maria@email.com",
    phone: "0414-1234567",
    role: "usuario",
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: 2,
    name: "Carlos Rodríguez",
    email: "carlos@email.com",
    phone: "0424-7654321",
    role: "usuario",
    createdAt: "2025-01-05T00:00:00Z",
  },
  {
    id: 3,
    name: "Recepcionista Demo",
    email: "recepcion@sweetmoments.com",
    role: "recepcionista",
    createdAt: "2024-12-01T00:00:00Z",
  },
  { id: 4, name: "Admin Demo", email: "admin@sweetmoments.com", role: "admin", createdAt: "2024-11-01T00:00:00Z" },
]

export const mockPromotions: Promotion[] = [
  {
    id: 1,
    name: "5 Cupcakes por $20",
    description: "Lleva 5 cupcakes por solo $20",
    discountType: "fixed",
    discountValue: 5,
    validFrom: "2025-01-01T00:00:00Z",
    validUntil: "2025-12-31T23:59:59Z",
    isActive: true,
  },
  {
    id: 2,
    name: "Docena de Cupcakes",
    description: "Docena de cupcakes por $50",
    discountType: "percentage",
    discountValue: 17,
    validFrom: "2025-01-01T00:00:00Z",
    validUntil: "2025-12-31T23:59:59Z",
    isActive: true,
  },
]

export const mockDashboardStats: DashboardStats = {
  totalOrders: 156,
  pendingOrders: 8,
  totalRevenue: 15780,
  todayRevenue: 520,
  totalProducts: 9,
  lowStockProducts: 2,
  totalUsers: 89,
  newUsersToday: 3,
}
